repo_url: https://github.com/lonnstyle/DiscordBotExt
repo_name: DiscordBotExt
site_author: lonnstyle
copyright: © 2021 lonnstyle
theme:
    name: readthedocs
    titles_only: true
nav:
    - 歡迎: index.md
    - 快速安裝: quickInstall.md
    - 指令擴展: ext.md
    - 現成的指令擴展:
        - admin.py: ext/admin.md
    - 關於:
        - 贊助: donate.md